[package]
name = "utlsrv"
version = "0.1.0"
authors = ["Carsten Nielsen <heycarsten@gmail.com>"]

[dependencies]
clap = "~2.31.2"
shiplift = "~0.4.0"
rusoto_core = "~0.36.0"
rusoto_ecs = "~0.36.0"
rusoto_ecr = "~0.36.0"
