#!/usr/bin/env bash
set -e

# Load up .env
set -o allexport
[[ -f .env ]] && source .env
set +o allexport

if [[ -n $1 ]]; then
  BASE_IMAGE_TAG="$1"
fi

if [[ -n $2 ]]; then
  IMAGE_TAG="$2"
fi

if [[ -n $3 ]]; then
  LOGIN_VOLUME="$3"
fi

if [[ -z $BASE_IMAGE_TAG ]] || [[ -z $IMAGE_TAG ]] || [[ -z $LOGIN_VOLUME ]]; then
  echo 'bin/build - builds docker images'
  echo 'usage: bin/build [BASE_IMAGE_TAG IMAGE_TAG LOGIN_VOLUME]'
  echo
else
  # Build base image
  docker build \
    --squash \
    -t "${BASE_IMAGE_TAG}:latest" \
    -f Dockerfile.base \
    .

  # Build final image
  docker build \
    --squash \
    -t "${IMAGE_TAG}:latest" \
    --build-arg base_image_tag="${BASE_IMAGE_TAG}:latest" \
    --build-arg login_volume="$LOGIN_VOLUME" \
    .
fi
